import Landing from '../components/Landing'
import Head from 'next/head'

export async function getStaticProps() {
   const res = await fetch(`${process.env.NEXT_PUBLIC_IKAIKACMS}/api/outnows`, {method: "GET"})
   const outnows = await res.json()
   const amount = outnows.data.length;

   return {
      props: {
         outnows,
         amount
      },
   };
}

export default function Home({outnows, amount}) {
   return (
      <>
      <Head>
         <title>Ikaika Records - Record label, audio services, and community</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing outnows={outnows} amount={amount} /> 
      </>
   )
}
