import Landing from '../components/Landing'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ikaika Records - Record label, audio services, and community</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing /> 
    </>
  )
}
